import type { ICropNFT } from '../models/CropNFT';

/**
 * Sample crop data for seeding MongoDB during development.
 * These crops represent real-world agricultural scenarios with full
 * blockchain metadata for Solana Explorer integration.
 */
export const cropSeeds: Array<any> = [
  {
    farmer: undefined as any, // Will be replaced with actual farmer ID
    cropName: 'Golden Harvest Basmati',
    nftName: 'Golden Harvest Basmati #101',
    nftSymbol: 'CROP',
    nftDescription: 'Blockchain verified basmati rice from Punjab, India.',
    cropType: 'Rice',
    farmLocation: 'Punjab, India',
    organicStatus: 'organic',
    seedInformation: 'Basmati-370 heirloom seed variety',
    fertilizersUsed: 'Organic compost, neem cake, vermicompost',
    pesticidesUsed: 'Neem spray, biological pest control',
    irrigationMethod: 'Drip irrigation with rainwater harvesting',
    cultivationDate: new Date(2026, 0, 15),
    harvestDate: new Date(2026, 4, 10),
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/basmati-101',
    mintAddress: 'BaFfBs4ixRm8W28dh9wpgJNTN14dLevYnY4YfT3jLvXr',
    transactionHash: '4jw6X8kpQ2zYvN5mL7hR9tDxJ3wFkP2vM8nL5sQ6tU7vW9yZ1aB3cD5eF7gH9i',
    verificationBadge: true,
    currentStage: 'delivered',
    consumerNotes: 'Premium quality basmati rice with excellent aroma and taste.',
  },
  {
    farmer: undefined as any,
    cropName: 'Sunrise Valencia Oranges',
    nftName: 'Sunrise Valencia Oranges #42',
    nftSymbol: 'CROP',
    nftDescription: 'Fresh organic Valencia oranges from Maharashtra, India.',
    cropType: 'Citrus',
    farmLocation: 'Nagpur, Maharashtra',
    organicStatus: 'organic',
    seedInformation: 'Valencia orange grafted seedlings',
    fertilizersUsed: 'Organic NPK blend, fish emulsion',
    pesticidesUsed: 'Copper fungicide, sulfur spray',
    irrigationMethod: 'Micro-sprinkler system',
    cultivationDate: new Date(2025, 8, 1),
    harvestDate: new Date(2026, 3, 20),
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/valencia-42',
    mintAddress: 'CiRmT9fK4nL2jP8sW5vQ1dX6yH3uA7mB9cN4eO2fL5k',
    transactionHash: '5kx7Y9lmQ3aZwN6nL8hR0tDxJ4wFkP3vM9nL6sQ7tU8vW0yZ2aB4cD6eF8gH0j',
    verificationBadge: true,
    currentStage: 'packed',
    consumerNotes: 'Hand-picked oranges at peak ripeness.',
  },
  {
    farmer: undefined as any,
    cropName: 'Organic Heirloom Tomatoes',
    nftName: 'Organic Heirloom Tomatoes #67',
    nftSymbol: 'CROP',
    nftDescription: 'Premium heirloom tomatoes from Karnataka farms.',
    cropType: 'Tomato',
    farmLocation: 'Bangalore, Karnataka',
    organicStatus: 'organic',
    seedInformation: 'Heirloom Roma, Beefsteak, Cherry tomato mix',
    fertilizersUsed: 'Cow manure, bone meal, seaweed extract',
    pesticidesUsed: 'Bacillus thuringiensis, neem oil',
    irrigationMethod: 'Drip irrigation with mulching',
    cultivationDate: new Date(2026, 1, 10),
    harvestDate: new Date(2026, 4, 5),
    image: 'https://images.unsplash.com/photo-1592841494240-ff3a5acd588d?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/tomato-67',
    mintAddress: 'DiSnU2kL5oP9rM6tV3wY8zC1aE4bF7gH0jK3lN6qR9s',
    transactionHash: '6ly8Z0nR4bAaXwO7pL9iS2uD5vE8fH1jK4mN7qR0tU3vW6yZ9aB2cD5eF7gH9i',
    verificationBadge: true,
    currentStage: 'harvested',
    consumerNotes: 'Mixed heirloom varieties with natural sweetness.',
  },
  {
    farmer: undefined as any,
    cropName: 'Malabar Black Pepper',
    nftName: 'Malabar Black Pepper #23',
    nftSymbol: 'CROP',
    nftDescription: 'Premium Malabar black pepper from Kerala spice farms.',
    cropType: 'Spice',
    farmLocation: 'Wayanad, Kerala',
    organicStatus: 'organic',
    seedInformation: 'Panniyur-1 pepper variety cuttings',
    fertilizersUsed: 'Coconut coir, cattle manure, potassium sulfate',
    pesticidesUsed: 'Sulphur dust, botanical extracts',
    irrigationMethod: 'Shade-grown with natural rainfall',
    cultivationDate: new Date(2024, 6, 1),
    harvestDate: new Date(2026, 2, 15),
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd6b6d8?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/pepper-23',
    mintAddress: 'EjToV3lM6nP9qR2tU5wX8yZ1aE4bF7gH0jK3lN6qR9s',
    transactionHash: '7mz9A1oS4bAaXwO7pL9iS2uD5vE8fH1jK4mN7qR0tU3vW6yZ9aB2cD5eF7gH9i',
    verificationBadge: true,
    currentStage: 'packed',
    consumerNotes: 'Whole black peppercorns with strong aroma.',
  },
  {
    farmer: undefined as any,
    cropName: 'Kashmir Saffron',
    nftName: 'Kashmir Saffron #15',
    nftSymbol: 'CROP',
    nftDescription: 'Finest grade Kashmir saffron from Pampore region.',
    cropType: 'Saffron',
    farmLocation: 'Srinagar, Kashmir',
    organicStatus: 'organic',
    seedInformation: 'Pure saffron crocus bulbs',
    fertilizersUsed: 'Organic sheep manure, bone meal',
    pesticidesUsed: 'Integrated pest management only',
    irrigationMethod: 'Traditional canal irrigation',
    cultivationDate: new Date(2025, 8, 1),
    harvestDate: new Date(2026, 9, 20),
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd6b6d8?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/saffron-15',
    mintAddress: 'FkUpW4mN7oQ0rS3uV6wX9yZ2aE5bF8gH1jK4lN7qR0s',
    transactionHash: '8na0B2pT5cAbBxP8qM0jT3vE6wF9gH2iJ5kL8mN1oU4vW7xZ0aB3cD6eF9gH1i',
    verificationBadge: true,
    currentStage: 'harvested',
    consumerNotes: 'Grade A Kashmiri saffron with premium quality.',
  },
  {
    farmer: undefined as any,
    cropName: 'Darjeeling Tea Leaves',
    nftName: 'Darjeeling Tea Leaves #88',
    nftSymbol: 'CROP',
    nftDescription: 'First flush Darjeeling tea from Himalayan estates.',
    cropType: 'Tea',
    farmLocation: 'Darjeeling, West Bengal',
    organicStatus: 'organic',
    seedInformation: 'Premium tea plant clones',
    fertilizersUsed: 'Coffee pulp, composted leaves, rock phosphate',
    pesticidesUsed: 'Biodynamic pest control',
    irrigationMethod: 'Natural hill slope water flow',
    cultivationDate: new Date(2025, 0, 15),
    harvestDate: new Date(2026, 2, 25),
    image: 'https://images.unsplash.com/photo-1597318972741-2fc2c1b42607?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/tea-88',
    mintAddress: 'GlVqX5nO8pR1sT4uV7wX0yZ3aE6bF9gH2jK5lN8qR1s',
    transactionHash: '9ob1C3qU6dAcCyQ9rN1kU4wF7xG0hI3jK6lM9nO2pV5yZ8aB1cD4eF7gH0i',
    verificationBadge: true,
    currentStage: 'delivered',
    consumerNotes: 'Premium first flush Darjeeling with floral notes.',
  },
  {
    farmer: undefined as any,
    cropName: 'Alphonso Mangoes',
    nftName: 'Alphonso Mangoes #34',
    nftSymbol: 'CROP',
    nftDescription: 'Premium King of Fruits - Alphonso mangoes from Ratnagiri.',
    cropType: 'Mango',
    farmLocation: 'Ratnagiri, Maharashtra',
    organicStatus: 'organic',
    seedInformation: 'Alphonso grafted saplings (15 years old)',
    fertilizersUsed: 'Farmyard manure, perlite, micronutrient blend',
    pesticidesUsed: 'Copper oxychloride, sulfur spray',
    irrigationMethod: 'Drip irrigation with fertigation',
    cultivationDate: new Date(2010, 3, 1),
    harvestDate: new Date(2026, 5, 15),
    image: 'https://images.unsplash.com/photo-1585518419759-31fca1e80088?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/mango-34',
    mintAddress: 'HmWrY6oP9qS2tU5vW8xY1zA4bE7cG0hI3kL6mN9oQ2r',
    transactionHash: '0pc2D4rV7eBdDzR0sO2lV5xG8yH1iJ4kL7mN0oP3qW6zZ9aB2cD5eF8gH1i',
    verificationBadge: true,
    currentStage: 'growing',
    consumerNotes: 'Awaiting harvest of premium Ratnagiri Alphonso mangoes.',
  },
  {
    farmer: undefined as any,
    cropName: 'Coconut & Coconut Oil',
    nftName: 'Coconut & Coconut Oil #56',
    nftSymbol: 'CROP',
    nftDescription: 'Virgin cold-pressed coconut oil from Kerala plantations.',
    cropType: 'Coconut',
    farmLocation: 'Thiruvananthapuram, Kerala',
    organicStatus: 'organic',
    seedInformation: 'Tall and dwarf hybrid coconut varieties',
    fertilizersUsed: 'Coir dust, fish meal, potassium nitrate',
    pesticidesUsed: 'Integrated coconut pest management',
    irrigationMethod: 'Drip irrigation with mulching',
    cultivationDate: new Date(2015, 5, 1),
    harvestDate: new Date(2026, 3, 30),
    image: 'https://images.unsplash.com/photo-1582803214987-db0fc5fb9180?auto=format&fit=crop&w=1200&q=80',
    metadataUri: 'https://api.cropchain.io/api/metadata/coconut-56',
    mintAddress: 'InXsZ7pQ0rT3uV6wX9yZ2aE5bF8cG1hI4jL7mN0oQ3r',
    transactionHash: '1qd3E5sW8fAeEaS1tP3mW6yH9zI2jK5lM8nO1pQ4rW7yZ0aB3cD6eF9gH2i',
    verificationBadge: true,
    currentStage: 'packed',
    consumerNotes: 'Virgin cold-pressed coconut oil with no additives.',
  },
];

/**
 * Sample farmer data for seeding - farmer accounts to link with crops
 */
export const farmerSeeds = [
  {
    name: 'Aarav Singh',
    email: 'aarav.singh@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Green Delta Farms',
    location: 'Punjab, India',
    bio: 'Sustainable rice farmer with 20 years of experience in organic cultivation.',
  },
  {
    name: 'Meera Deshmukh',
    email: 'meera.deshmukh@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Valley Fresh Co.',
    location: 'Nagpur, Maharashtra',
    bio: 'Citrus specialist growing premium oranges and lemons.',
  },
  {
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Green Valleys Organic',
    location: 'Bangalore, Karnataka',
    bio: 'Organic vegetable farmer focusing on heirloom varieties.',
  },
  {
    name: 'Priya Menon',
    email: 'priya.menon@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Spice Route Organic',
    location: 'Wayanad, Kerala',
    bio: 'Traditional spice farmer preserving heritage crops.',
  },
  {
    name: 'Ghulam Nabi',
    email: 'ghulam.nabi@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Kashmir Heritage Farms',
    location: 'Srinagar, Kashmir',
    bio: 'Premium saffron cultivator with family legacy of 50 years.',
  },
  {
    name: 'Deepak Roy',
    email: 'deepak.roy@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Himalayan Tea Estate',
    location: 'Darjeeling, West Bengal',
    bio: 'Tea estate manager producing first flush Darjeeling.',
  },
  {
    name: 'Vikram Sawant',
    email: 'vikram.sawant@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Coastal Orchards',
    location: 'Ratnagiri, Maharashtra',
    bio: 'Mango orchard owner specializing in Alphonso varieties.',
  },
  {
    name: 'Lakshmi Nair',
    email: 'lakshmi.nair@farmmail.com',
    password: 'Test@123456',
    role: 'farmer' as const,
    farmName: 'Tropical Farms Kerala',
    location: 'Thiruvananthapuram, Kerala',
    bio: 'Coconut and coconut oil producer using traditional methods.',
  },
];
